aherrmann/rules_zig

zig/private/zig_binary.bzl, zig/private/zig_library.bzl, zig/private/zig_test.bzl, zig/tests/package-binary/BUILD.bazel, zig/tests/package-binary/data.zig, zig/tests/package-binary/main.zig, zig/tests/rules_test.bzl
The progress message of a `zig_binary|library|test` build did not always display the correct root source file. For example, on targets with package dependencies one of the package dependencies' source file was listed instead.
This change fixes that by enforcing a preorder on the action inputs.
- Analysis test for progress message with package
- fix: set inputs order to preorder
=> fix: root source file in progress message

zig/tests/integration_tests/integration_tests_runner.zig
Introduced in https://github.com/aherrmann/rules_zig/pull/108
=> fix: typos in reproducibility tests

.bazelrc, .bazelrc.common, .github/workflows/ci.yaml, e2e/workspace/.bazelrc, e2e/workspace/BUILD, e2e/workspace/c-sources/BUILD.bazel, e2e/workspace/configure-mode/BUILD.bazel, e2e/workspace/configure-target/BUILD.bazel, e2e/workspace/configure-threaded/BUILD.bazel, e2e/workspace/data-dependencies/BUILD.bazel, e2e/workspace/embed-file/BUILD.bazel, e2e/workspace/linker-script/BUILD.bazel, e2e/workspace/multiple-sources-and-packages-test/BUILD.bazel, e2e/workspace/multiple-sources-binary/BUILD.bazel, e2e/workspace/simple-binary/BUILD.bazel, e2e/workspace/simple-test/BUILD.bazel, e2e/workspace/transitive-zig-packages-binary/BUILD.bazel, e2e/workspace/zig-package-binary/BUILD.bazel
- factor out common config and use it in e2e too
- Size test size attributes in e2e tests
- Configure bzlmod in .bazelrc.user
=> chore: factor out common Bazel config and use in e2e

README.md
- Expand the installation instructions
- Document examples before reference docs
- Refer to release notes for install instructions
- Remove the early development warning
=> docs: Install instructions and status in README

e2e/workspace/link-dependencies/static-library/BUILD.bazel
Test that symbols of dependency libraries are not inlined into the output archive.
=> test: static library linking behavior

util/BUILD.bazel
The locale configuration had an impact on the sorting order. Pinning the corresponding locale setting `LC_COLLATE` to a stable value such as `C.UTF-8` solves the issue.
=> chore: Reproducible update_deleted_packages

e2e/workspace/runfiles-library/dependency/main.zig, e2e/workspace/runfiles-library/main.zig, zig/runfiles/src/Directory.zig, zig/runfiles/src/Runfiles.zig, zig/tests/integration_tests/workspace/runfiles/main.zig
Part of #86
- Explicit alloc: rlocation --> rlocationAlloc
- rlocationUnmapped --> rlocationUnmappedAlloc
- non-allocating rlocation function
- Use RPath.init for rpath repo splitting
- Factor out rpath remapping
- Add non-allocating variant of rlocation
- Consistent out_buffer argument position
- Test non-allocating rlocation variant
=> feat: non-allocating variant of rlocation

e2e/workspace/runfiles-library/BUILD.bazel, e2e/workspace/runfiles-library/main.zig, zig/runfiles/src/Manifest.zig, zig/runfiles/src/Runfiles.zig
Part of #86
Bazel merges runfiles at the top-level. If nested processes need to access runfiles, then the environment must contain the relevant varibles to point to the top-level runfiles manifest or directory.
- runfiles manifest: remember path
- Expose the runfiles environment variables
- Unit test runfiles directory
- e2e test: nested binary runfiles
=> feat: expose runfiles environment variables

e2e/workspace/zig-docs/main.zig, zig/private/common/zig_build.bzl, zig/private/common/zig_docs.bzl
Set the `--main-pkg-path` flag to `.` (the execution root).
- fix: Set the --main-pkg-path flag
- fix: e2e docs test autodocs guide path
=> fix: resolve zig-autodoc-guide correctly

README.md, e2e/workspace/runfiles-library/BUILD.bazel, e2e/workspace/runfiles-library/dependency/main.zig, e2e/workspace/runfiles-library/main.zig, zig/runfiles/BUILD.bazel, zig/runfiles/guide.md, zig/runfiles/runfiles.zig, zig/runfiles/src/Runfiles.zig, zig/runfiles/src/discovery.zig, zig/runfiles/test-data.txt, zig/tests/integration_tests/workspace/runfiles/main.zig
Part of #86
- Generate Zig docs for the runfiles library
- Add doctest for runfiles library
- Add a autodoc guide to the runfiles library
- Expand runfiles API docs
- Runfiles.create return optional
- Move runfiles path constants into discovery
- Link to the guide from the API docs
- Link to runfiles docs from README
- Test runfiles docs build in e2e test
- fix comment
=> docs: runfiles library user guide

e2e/workspace/runfiles-library/dependency/main.zig, e2e/workspace/runfiles-library/main.zig, zig/runfiles/guide.md, zig/runfiles/runfiles.zig, zig/runfiles/src/Runfiles.zig, zig/tests/integration_tests/workspace/runfiles/main.zig
Closes #86
With `Runfiles.withSourceRepo` users can specify the source repository name once and then perform multiple runfile path lookups relative to the same source repository.
- source --> source_repo
- introduce `withSourceRepo` function
=> feat: introduce Runfiles.withSourceRepo

zig/BUILD.bazel, zig/extensions.bzl, zig/private/common/BUILD.bazel, zig/private/common/semver.bzl, zig/tests/BUILD.bazel, zig/tests/semver_test.bzl
Part of #257
- **Add unit test suite for semver module**
- **Parse main components**
- **Handle pre-release and build components**
- **feat: support reversed semver sort**
- **test: reversed semver sort**
- **fix zig version sort**
- **update generated files**
=> feat: sort specified Zig SDK versions by semantic version

MODULE.bazel, zig/extensions.bzl
Part of #257
Since rules_zig now supports multiple Zig SDK versions and orders them by semantic versions precedence, the core module (`@rules_zig`) should not always explicitly set a Zig SDK version, as that would prevent any root module from specifying a lower version as the default version.
Instead, the `zig` module extension implicitly sets a default version if none is specified by any module.
- **No Zig version in core module**
- **feat: implicit default Zig SDK version**
=> feat: implicit default Zig SDK version

.github/workflows/ci.yaml
As documented in https://github.com/actions/runner/issues/980#issuecomment-777057271
This occurs when a PR is marked as depending on another PR, has that other PR's branch as its base branch, and GitHub then automatically changes the base branch after the first PR is merged.
=> chore: trigger CI on base branch change

e2e/workspace/link-dependencies/shared-library/BUILD.bazel, zig/private/common/cdeps.bzl
Closes #274
Changes the command line to link a dynamic library from `some/libfoo.dylib` to `-Lsome -lfoo`.
- **Revert "skip dylib linking on MacOS with 0.12.0"**
- **Expand dynamic libraries to -L / -l flags**
- **uniquify rpath arguments**
- **Deduplicate library search path flags**
=> fix: dynamic linking on MacOS with Zig 0.12.0

zig/runfiles/BUILD.bazel
Closes #273
This reverts commit fddc80dc8f5e184bb8ad6b5b8758ad3bef55d043.
I am no longer able to reproduce the issue. It is unclear what caused it. It may be worthwhile to inspect items cached in the remote cache for whether they carry references to the global or local Zig cache directory and if any of these pathnames are non-reproducible.
=> test: re-enable Zig docs generation for Zig 0.12.0 on MaCOS

.bcr/presubmit.yml
Closes #277
- **BCR presubmit - add rules_zig module tasks**
- **BCR presubmit - change Bazel versions to 6.x, 7.x**
=> chore: update the BCR presubmit configuration

.github/workflows/zig_update.yaml, util/BUILD.bazel, util/update_zig_versions.py, zig/private/BUILD.bazel, zig/private/bzlmod/zig.bzl, zig/private/versions.bzl, zig/private/versions.bzl.tpl, zig/private/versions.json, zig/repositories.bzl, zig/tests/bzlmod_zig_test.bzl
Generate and check in a JSON file that tracks the available Zig versions.
The format is compatible with the upstream index format at https://ziglang.org/download/index.json.
The zig module extension no longer depends on the `TOOL_VERSIONS` constant and instead reads the JSON file in its module extension implementation function.
This is a step toward user defined Zig versions and relevant to #76.
- **sort imports**
- **update_zig_versions.py: generate JSON not bzl**
- **Generate versions.json file**
- **update the Zig update workflow**
- **Generate versions.bzl based on JSON data**
- **Generate a new JSON based versions.bzl**
- **Consistent JSON indentation**
- **Consistent JSON encoding - line ending**
- **Fix missing return value**
- **integrity -> sha256**
- **Update Zig version update …
=> refactor: Track Zig versions in JSON file

MODULE.bazel, README.md, WORKSPACE
This is required for #290, which needs `json.decode(..., default=...)`, i.e. the `default` argument to `json.decode`. Unfortunately, that feature is not represented in https://github.com/bazel-contrib/bazel_features, so there is also no good way to check for the availability of this feature.
- **chore!: drop Bazel 6 support**
- **docs: Update README**
BREAKING CHANGE: Bazel versions <7 are no longer supported
=> chore!: drop Bazel 6 support

MODULE.bazel, docs/extensions.md, zig/private/bzlmod/zig.bzl, zig/private/common/semver.bzl, zig/tests/bzlmod_zig_test.bzl, zig/tests/integration_tests/BUILD.bazel, zig/tests/integration_tests/workspace/MODULE.bazel, zig/tests/integration_tests/workspace/extra-versions.json
Depends on #291
Closes #76
To register a nightly toolchain a user must add a version index JSON file (as a available on https://ziglang.org/download/index.json) to their project, register it using the `zig.index(file = ...)` tag, and then register the version using `zig.toolchain(zig_version = ...)`.
This also provides support for the broader interpretation of #72.
- **Add the zig.index tag.**
- **Add doc string for the zig.toolchain tag**
- **handle_tags --> handle_toolchain_tags**
- **refactor: handle_toolchain_tags takes module list**
- **docs: update generated API docs**
- **feat: Support user defined Zig version index files**
- **Support JSON parsing error reporting**
- **Test Zig version index parsing**
- **Test JSON parsing failure cases**
- **Parse nightly version**
- **Test full …
=> feat: support user defined version index (incl. pre-release)

.bazelrc.common, .bazelrc.flags, .bazelrc.remote
With Bazel 6 support dropped some experimental flags can be replaced by their non-experimental versions. 
- **Redundant --noincompatible_sandbox_hermetic_tmp**
- **Add --zig_version flag alias**
- **Replace --experimental_remote_build_event_upload**
- **Sort --bes_* flags**
- **Replace --experimental_remote_cache_compression**
=> chore: update .bazelrc configuratio

zig/private/common/cdeps.bzl, zig/private/common/zig_build.bzl, zig/private/common/zig_docs.bzl
Adds a RUNPATH to support loading shared libraries from runfiles trees when the entrypoint is executed from outside the runfiles tree, e.g. in `genrule` build actions.
This issue was previously dormant because the shared library is still available under an alternative RUNPATH in local execution.
Otherwise running dynamically linked binaries fails in remote execution setups with errors of the form:
```
bazel-out/k8-opt-exec-ST-74b705998179/bin/link-dependencies/shared-library/binary: error while loading shared libraries: libadd.so: cannot open shared object file: No such file or directory
```
The library `libadd.so` is part of the action inputs, but only under the runfiles tree next to `binary` in `binary.runfiles/_main/_solib_k8/...`.
See …
=> fix: load shared libraries from runfiles

.bazelrc.remote, .github/workflows/ci.yaml, MODULE.bazel, WORKSPACE, WORKSPACE.bzlmod, e2e/workspace/MODULE.bazel, e2e/workspace/WORKSPACE.bazel, e2e/workspace/WORKSPACE.bzlmod, e2e/workspace/configure-mode/BUILD.bazel, e2e/workspace/configure-threaded/BUILD.bazel, e2e/workspace/link-dependencies/static-library/BUILD.bazel, e2e/workspace/simple-library/BUILD.bazel, e2e/workspace/simple-shared-library/BUILD.bazel, internal_deps.bzl, util/BUILD.bazel
- Enables remote execution on CI.
- Installs the BuildBuddy platform and toolchain as a dev-dependency required for C/C++ targets, primarily protoc.
- **Enable remote execution**
- **Configure hermetic_cc_toolchain**
- **Configure more concurrent jobs for RE**
- **Revert "Configure hermetic_cc_toolchain"**
- **Install and configure BuildBuddy toolchains**
- **Remove -j from nm invocations**
- **Tag buildifier_test as no-remote-exec**
- **Make remote configuration explicit**
- **Enable remote execution on CI**
=> chore!: enable remote execution on CI for Linux

.github/actions/test/action.yaml, .github/workflows/ci.yaml
Create a composite workflow for the actual CI pipeline and simplify the CI matrix by defining separate jobs for separate main parameter axes.
- **Factor out GitHub CI into composite workflow**
- **Consistent Matrix parameter spelling**
- **Load Zig versions into GH workflow**
- **Dedicated axis for Bazel versions**
- **Dedicated Zig version tests**
- **Dedicated integration tests**
- **Avoid duplicate Bazel and Zig latest version test**
- **all tests depends on zig versions**
=> chore: refactor CI workflow

zig/tests/integration_tests/BUILD.bazel, zig/tests/integration_tests/workspace/MODULE.bazel, zig/tests/integration_tests/workspace/extra-versions.json
The download of the previously configured version was no longer available.
=> chore: update Zig HEAD version test

.bazelrc, .bazelrc.remote, .github/actions/test/action.yaml, .github/workflows/ci.yaml, WORKSPACE, e2e/workspace/.bazelrc, e2e/workspace/workspace_status.sh, internal_deps.bzl, workspace_status.sh, zig/tests/integration_tests/.bazelrc.meta.tpl, zig/tests/integration_tests/BUILD.bazel, zig/tests/integration_tests/workspace/.bazelrc
Anonymous BuildBuddy builds are now deprecated.
This switches the build and CI to use an access token. 
- **Configure BuildBuddy account**
- **Configure repository secret**
- **Set up build metadata through workspace status**
=> chore: configure BuildBuddy credentials

MODULE.bazel, WORKSPACE
rules_cc >=0.0.12 requires Bazel >=7.1.0 to specifiy `extension_metadata(reproducible=...)`.
=> chore: Bump minimal Bazel version to 7.1.0

.github/workflows/ci.yaml, .github/workflows/release.yml, .pre-commit-config.yaml
- **chore: update GH action validator**
- **expect BuildBuddy token on CI workflow_call**
- **pass the BuildBuddy token from release workflow**
=> chore: pass token secrets from release workflow

.bcr/presubmit.yml, .github/actions/test/action.yaml, .github/workflows/ci.yaml, e2e/workspace/zig-docs/BUILD.bazel, zig/runfiles/BUILD.bazel, zig/tests/zig-docs/BUILD.bazel
Zig docs builds frequently failed on CI, see #273. Two cases were observed:
1. Zig docs builds failed when remote execution was enabled.
2. Zig docs builds failed locally on MacOS with Zig version 0.12.0.
The first case is addressed by moving Zig docs build tests into a separate CI job and disabling remote execution in that case.
The second case is addressed by marking Zig docs targets as incompatible with Zig version 0.12.0 and MacOS systems.
This is a workaround, not a proper fix of #273.
- **Remove test.sh check from CI script**
- **Tag all Zig documentation targets**
- **Use tag filters to skip Zig docs builds**
- **Add separate Zig docs tests**
- **Exclude zig-docs in presubmit.yml**
- **build_test target for runfiles docs**
- **Zig docs tests for all Zig versions using transitions** …
=> fix: work around Zig docs build failures

docs/rules.md, zig/private/common/zig_build.bzl, zig/tests/compiler_runtime/BUILD.bazel, zig/tests/compiler_runtime/main.zig, zig/tests/rules_test.bzl
The `compiler_runtime` attribute accepts the values
- "include" to pass "-fcompiler-rt",
- "exclude" to pass "-fno-compiler-rt", and
- "default" to rely on the Zig compiler's default.
---
- **feat: Add compiler_runtime attribute to control -fcompiler-rt**
- **compiler_runtime test targets**
- **Analysistests for compiler_runtime attribute**
=> feat: Add compiler_runtime attribute to control -fcompiler-rt

.github/actions/test/action.yaml, .github/workflows/ci.yaml
- **fix: GitHub action remoteEnabled condition**
- **skip MacOS Zig doc tests**
Context: https://github.com/aherrmann/rules_zig/issues/273#issuecomment-2746948898
=> ci: skip Zig docs pipeline

util/update_zig_versions.py
=> chore: exclude Zig 0.13.0 in automated update

zig/private/common/zig_build.bzl, zig/private/common/zig_docs.bzl, zig/private/providers/zig_module_info.bzl, zig/tests/module_info_test.bzl
Part of #480 
This PR refactors `ZigModuleInfo` so that --dep and -M cli args are computed transitively from 1 single ZigModuleInfo root.
While doing this, I found that the _mock_args implementation was not compliant with the actual `ctx.actions.args` implementation, especially when using `depset`. 
I took the opportunity to rewrite those tests using custom rules and `diff_test` so that we are sure that what we test is actually what is going to end up in the action run.
=> Refactor ZigModuleInfo to have a single arg rendering path

.bazelversion, BUILD.bazel, MODULE.bazel, e2e/workspace/.bazelversion, e2e/workspace/BUILD, e2e/workspace/MODULE.bazel, e2e/workspace/configure-target/BUILD.bazel, e2e/workspace/configure-target/defs.bzl, zig/private/resolved_target_toolchain.bzl, zig/private/resolved_toolchain.bzl, zig/tests/platforms/BUILD.bazel, zig/tests/platforms/defs.bzl, zig/tests/target_platform_test.bzl
- **chore: update to Bazel 9 pre-release**
- **Remove incompatible_use_toolchain_transition**
=> feat: support Bazel 9 pre-release

e2e/workspace/configure-threaded/BUILD.bazel, e2e/workspace/configure-use_cc_common_link/shared-library/BUILD.bazel, e2e/workspace/configure-use_cc_common_link/static-library/BUILD.bazel, e2e/workspace/link-dependencies/static-library/BUILD.bazel, e2e/workspace/linkopts-attr/BUILD.bazel
Skip library symbol tests with Zig 0.15.1, corresponding CI failure:
https://buildkite.com/bazel/bcr-presubmit/builds/20259/steps/canvas?jid=0199874b-b8d2-4441-914e-634cf422908e#0199874b-b8d2-4441-914e-634cf422908e/447-492
Skip linkopts attribute tests with Zig 0.15.1, corresponding CI failure:
https://buildkite.com/bazel/bcr-presubmit/builds/20276/steps/canvas?jid=01998ace-1c3b-4c4e-9fb1-1293a5a2c19f#01998ace-1c3b-4c4e-9fb1-1293a5a2c19f/444-491
Skip configure use_cc_common_link check, corresponding CI failure
https://buildkite.com/bazel/bcr-presubmit/builds/20277/steps/canvas?jid=01998ae0-bde8-4e77-8089-4bfb1cf5785a#01998ae0-bde8-4e77-8089-4bfb1cf5785a/447-497
=> fix: avoid Zig 0.15.1 malformed archive issues
